# Generated by Django 4.1.6 on 2023-02-01 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("laboratories", "0001_initial"),
        ("medicines", "0002_medicines_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicines",
            name="laboratori_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to="laboratories.laboratory",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="medicines", name="name", field=models.CharField(max_length=50),
        ),
    ]
